export const th = {
  section:              (d) => d ? "bg-slate-950" : "bg-slate-50",
  blob:                 (d) => d ? "bg-gradient-to-r from-cyan-500/20 to-blue-500/20" : "bg-gradient-to-r from-cyan-300/30 to-blue-300/30",
  particle:             (d) => d ? "bg-cyan-400" : "bg-cyan-500",
  badgeWrapper:         (d) => d ? "inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-cyan-400/30 bg-cyan-400/10" : "inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-cyan-500/30 bg-cyan-50",
  badgeText:            (d) => d ? "text-cyan-300 font-semibold text-xs" : "text-cyan-700 font-semibold text-xs",
  typeAnimation:        (d) => d ? "text-cyan-400 font-semibold text-sm" : "text-cyan-600 font-semibold text-sm",
  heading:              (d) => d ? "text-white font-black leading-[1.08] text-2xl sm:text-3xl lg:text-4xl xl:text-5xl" : "text-slate-900 font-black leading-[1.08] text-2xl sm:text-3xl lg:text-4xl xl:text-5xl",
  headingGradient:      ()  => "bg-gradient-to-r from-cyan-400 via-blue-500 to-cyan-400 bg-clip-text text-transparent",
  description:          (d) => d ? "mt-3 text-slate-300 text-sm leading-6 max-w-lg" : "mt-3 text-slate-600 text-sm leading-6 max-w-lg",
  primaryButton:        ()  => "group inline-flex items-center px-5 py-2.5 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 text-white text-sm font-medium shadow-lg hover:shadow-xl hover:-translate-y-0.5 transition-all duration-300",
  secondaryButton:      (d) => d ? "inline-flex items-center gap-2 px-5 py-2.5 rounded-xl border border-white/20 bg-white/10 backdrop-blur-xl text-sm font-medium text-white hover:bg-white/20 transition-all duration-300" : "inline-flex items-center gap-2 px-5 py-2.5 rounded-xl border border-slate-300 bg-white text-sm font-medium text-slate-900 hover:bg-slate-100 transition-all duration-300 shadow-sm",
  secondaryButtonIconWrap: (d) => d ? "w-7 h-7 rounded-full bg-white/10 flex items-center justify-center" : "w-7 h-7 rounded-full bg-slate-100 flex items-center justify-center",
  statCard:             (d) => d ? "bg-white/5 backdrop-blur-xl border border-white/10 rounded-xl p-3" : "bg-white border border-slate-200 rounded-xl p-3 shadow-sm",
  statIcon:             (d) => d ? "text-cyan-400 text-xl mb-1.5" : "text-cyan-600 text-xl mb-1.5",
  statValue:            (d) => d ? "text-white font-bold text-lg" : "text-slate-900 font-bold text-lg",
  statLabel:            (d) => d ? "text-slate-400 text-xs mt-0.5" : "text-slate-500 text-xs mt-0.5",
  avatarBorder:         (d) => d ? "w-7 h-7 rounded-full border-2 border-white" : "w-7 h-7 rounded-full border-2 border-slate-50",
  starRow:              ()  => "flex gap-0.5 text-yellow-400 text-xs",
  reviewText:           (d) => d ? "text-slate-300 text-xs" : "text-slate-600 text-xs",
  companiesEyebrow:     (d) => d ? "text-cyan-400 uppercase tracking-[0.3em] text-xs font-semibold" : "text-cyan-600 uppercase tracking-[0.3em] text-xs font-semibold",
  companiesHeading:     (d) => d ? "text-white text-xl md:text-2xl font-bold mt-1" : "text-slate-900 text-xl md:text-2xl font-bold mt-1",
  companiesSubtext:     (d) => d ? "text-slate-400 mt-2 max-w-xl mx-auto text-sm" : "text-slate-500 mt-2 max-w-xl mx-auto text-sm",
  fadeLeft:             (d) => d ? "absolute left-0 top-0 z-10 h-full w-20 bg-gradient-to-r from-slate-950 to-transparent pointer-events-none" : "absolute left-0 top-0 z-10 h-full w-20 bg-gradient-to-r from-slate-50 to-transparent pointer-events-none",
  fadeRight:            (d) => d ? "absolute right-0 top-0 z-10 h-full w-20 bg-gradient-to-l from-slate-950 to-transparent pointer-events-none" : "absolute right-0 top-0 z-10 h-full w-20 bg-gradient-to-l from-slate-50 to-transparent pointer-events-none",
  logoCard:             (d) => d ? "flex-shrink-0 w-36 h-20 rounded-2xl bg-white/5 backdrop-blur-xl border border-white/10 flex items-center justify-center shadow-xl hover:border-cyan-400/40 transition-all duration-300" : "flex-shrink-0 w-36 h-20 rounded-2xl bg-white border border-slate-200 flex items-center justify-center shadow-md hover:border-cyan-500/40 transition-all duration-300",
  logoImage:            (d) => d ? "h-8 object-contain transition duration-300" : "h-8 object-contain grayscale opacity-70 hover:grayscale-0 hover:opacity-100 transition duration-300",

  // ✅ Newly added — used in EnrollmentForm and other components
  textPrimary:          (d) => d ? "text-white" : "text-slate-900",
  textSecondary:        (d) => d ? "text-cyan-300 border-cyan-400/30 bg-cyan-400/10" : "text-cyan-700 border-cyan-500/30 bg-cyan-50",
  card:                 (d) => d ? "bg-white/5 border-white/10" : "bg-white border-slate-200",
};